### ISSUE TITLE
updating bazel dep automatically?

### ISSUE THREAD

**Issue by MalloZup** [ereslibre/kubernetes-cluster-vagrant#2]
so basically i changed a file in `k8s` repo, and then i couldn't build with bazel.

the solution was running `./hack/update-bazel.sh`. Maybe we should run it auto-magically by `make artifacts`

**Comment by ereslibre** [comment]
I think this would add overhead for every operation when only sometimes you really need to run `hack/update-bazel.sh`, `hack/update-gofmt.sh` or `hack/update-generated-docs.sh`. It's also always an open question which one of those should be ran when you do a `make debs`, `make images` or `make artifacts`.

I think it's a better approach to not do any call to any `hack` script automatically from any target in this project so the developer can choose when they want to run it, keeping the build targets on this project faster everytime.

**Comment by MalloZup** [comment]
Yop is was suggestion agree on it closing thx 🦄
